language: ruby
rvm:
  - 2.1.1
branches:
  only:
    - master
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/config.yml.example config/config.yml
  - RAILS_ENV=test bundle exec rake db:migrate --trace
script:
  - bundle exec rspec --color --format documentation
