language: ruby
rvm:
  - 2.1.0
branches:
  only:
    - master
notifications:
  email:
    on_success: change
    on_failure: change
script:
  - "cp config/database.yml.example config/database.yml"
  - "cp config/config.yml.example config/config.yml"
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
